version: "2.4"

services: 
  express:
    build:
      context: .
      target: dev
      args:
        - NODE_ENV=development
      dockerfile: ./express.Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./ipam/.:/node/app
      - /node/app/node_modules
    env_file:
      - ./.env/app.development.env

  mongo:
    build:
      context: .
      dockerfile: ./mongo.Dockerfile
    command: --auth
    ports: 
      - 37017:27017
    env_file:
      - ./.env/app.development.env

  scanner:
    build:
      context: .
      target: dev
      args:
        - NODE_ENV=development
      dockerfile: ./scanner.Dockerfile
    volumes:
      - ./scanner/.:/node/app
      - /node/app/node_modules
    env_file:
      - ./.env/app.development.env
